version: 2.1
jobs:
  build:
    docker:
      - image: alphine:3.7
    steps:
      - run:
        name: 最初のステップ
        command: |
          echo 'Hello World !'
          echo 'This is the delivery pipeline'
